web/router.ex
defmodule Conds.Router do
  use Conds.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", Conds do
    pipe_through :browser

    get "/", PageController, :index

    resources "/joint_owner", JointOwnerController
    resources "/apartments", ApartmentController
    resources "/buildings", BuildingController
    resources "/condos", CondominiumController
    resources "/resources", ResourceController
    resources "/events", EventController
  end
end

web/views/layout_view.ex
defmodule Conds.LayoutView do
  use Conds.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Conds!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-tabs">
            <li><a href="<%= page_path(@conn, :index) %>">Home</a></li>
            <li><a href="<%= joint_owner_path(@conn, :index) %>">Condôminos</a></li>
            <li><a href="<%= apartment_path(@conn, :index) %>">Apartamentos</a></li>
            <li><a href="<%= building_path(@conn, :index) %>">Prédios</a></li>
            <li><a href="<%= condominium_path(@conn, :index) %>">Condomínios</a></li>
            <li><a href="<%= resource_path(@conn, :index) %>">Recursos</a></li>
            <li><a href="<%= event_path(@conn, :index) %>">Eventos</a></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>